# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  clang-tidy:
    name: Test on OS ${{ matrix.os }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.so }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install
      run: |
        sudo add-apt-repository -u 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        sudo apt-get update
        sudo apt-get install -y llvm-10 clang-tidy-10 clang-10
        sudo apt install cmake
        sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-10 100
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 100

    # Runs a set of commands using the runners shell
    - name: Run tidy
      run: |
        python3 tests/ci_build/tidy.py --tidy-version=10 --cuda=0
